-- General editor options
vim.opt.encoding = 'utf-8'
vim.opt.fileencoding = 'utf-8'
vim.opt.termguicolors = true -- Enable true colors in the terminal
vim.opt.number = true        -- Show line numbers
vim.opt.relativenumber = true -- Show relative line numbers
vim.opt.expandtab = true     -- Use spaces instead of tabs
vim.opt.tabstop = 4          -- Number of spaces a tab counts for
vim.opt.shiftwidth = 4       -- Number of spaces to use for autoindent
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.wrap = false         -- Don't wrap lines
vim.opt.scrolloff = 8        -- Keep 8 lines above/below cursor when scrolling
vim.opt.signcolumn = 'yes'   -- Always show the sign column
vim.opt.clipboard = 'unnamedplus' -- Use system clipboard
vim.opt.splitright = true    -- Split vertical window to the right
vim.opt.splitbelow = true    -- Split horizontal window to the bottom
vim.opt.hidden = true        -- Allow background buffers
vim.opt.updatetime = 300     -- Faster completion popups
